-- FIXME: This is outdate and just gotta wiat til primeagen finishes this code ig

-- local mark = require("harpoon.mark")
-- local ui = require("harpoon.ui")
--
-- -- Add files
-- vim.keymap.set("n", "<leader>a", function() mark.add_file() end)
--
-- -- Toggle quick menu
-- vim.keymap.set("n", "<leader>m", function() ui.toggle_quick_menu() end)
--
-- -- Navigation keybinds
-- vim.keymap.set("n", "<C-h>", function() ui.nav_file(1) end)
-- vim.keymap.set("n", "<C-j>", function() ui.nav_file(2) end)
-- vim.keymap.set("n", "<C-k>", function() ui.nav_file(3) end)
-- vim.keymap.set("n", "<C-l>", function() ui.nav_file(4) end)
